ICONS = {
    "scan": "",
    "target": "◎",
    "status": "✅",
    "running": "⏳",
    "elapsed": "⏱️",
    "risk": "⚠️",
    "summary": "▣",
    "findings": "○",
    "assets": "▥",
    "ai": "✦",
    "report": "",
    "success": "✅",
    "warning": "⚠️",
    "error": "❌",
    "info": "ℹ️",
    "settings": "⚙️",
    "upload": "",
    "history": "",
    "home": "",
    "cancel": "❌",
    "back": "⬅️",
    "complete": "✅",
    "nmap": "⌁",
    "nuclei": "◇",
    "bbot": "◆",
    "observation": "○",
    "attack_path": "⟶",
    "mongrel_ai": "✦",
    "investigation": "▤",
    "completed": "✓",
    "saved": "▥",
    "statistics": "▦",
    "security": "⌾",
    "comparison": "▦",
    "impact": "⚠️",
}


def icon(name: str) -> str:
    return ICONS.get(name, "")
